### ISSUE TITLE
Could not start video recording...

### ISSUE THREAD

**Issue by charlesbel** [HBiSoft/HBRecorder#10]
Hi, I was testing your very interesting library with a simple code provided in the README :

```
public class ScreenRecorder extends AppCompatActivity implements HBRecorderListener {

    private static final int SCREEN_RECORD_REQUEST_CODE = 12345;
    HBRecorder hbRecorder;

    Button button10, button11;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.screen_recorder);

        button10 = (Button) findViewById(R.id.button10);
        button11 = (Button) findViewById(R.id.button11);


        button10.setOnClickListener(new View.OnClickListener() {
            @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
            @Override
            public void onClick(View v) {
                startRecordingScreen();
            }
        });

        button11.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                hbRecorder.stopScreenRecording();
            }
        });

        //Init HBRecorder
        hbRecorder = new HBRecorder(this, this);
    }

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    private void startRecordingScreen() {
        MediaProjectionManager mediaProjectionManager = (MediaProjectionManager) getSystemService(Context.MEDIA_PROJECTION_SERVICE);
        Intent permissionIntent = mediaProjectionManager != null ? mediaProjectionManager.createScreenCaptureIntent() : null;
        startActivityForResult(permissionIntent, SCREEN_RECORD_REQUEST_CODE);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == SCREEN_RECORD_REQUEST_CODE) {
            if (resultCode == RESULT_OK) {
                Toast.makeText(this, "Authorization granted", Toast.LENGTH_LONG).show();
                //Start screen recording
                hbRecorder.startScreenRecording(data, resultCode, this);

            }
        }
    }

    @Override
    public void HBRecorderOnComplete() {

    }

    @Override
    public void HBRecorderOnError(int errorCode, String reason) {

    }
}
```

But when I try to start the recording, I see the Recording Prompt message from Android, I click on Start Now and the app crash. 

On the Log I can see the following errors : 
```
2020-05-03 22:26:19.854 23343-23343/fr.gooddev.totalspy E/MediaRecorder: SurfaceMediaSource could not be initialized!
2020-05-03 22:26:19.855 23343-23343/fr.gooddev.totalspy E/MediaRecorder: start called in an invalid state: 4
2020-05-03 22:26:19.902 23343-23343/fr.gooddev.totalspy D/AndroidRuntime: Shutting down VM
2020-05-03 22:26:19.903 23343-23343/fr.gooddev.totalspy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.gooddev.totalspy, PID: 23343
    java.lang.RuntimeException: Unable to stop service com.hbisoft.hbrecorder.ScreenRecordService@c2e5f75: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.projection.MediaProjection.stop()' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:4136)
        at android.app.ActivityThread.access$1900(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1896)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.projection.MediaProjection.stop()' on a null object reference
        at com.hbisoft.hbrecorder.ScreenRecordService.resetAll(ScreenRecordService.java:421)
        at com.hbisoft.hbrecorder.ScreenRecordService.onDestroy(ScreenRecordService.java:407)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:4116)
        at android.app.ActivityThread.access$1900(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1896) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

I am using the last version of your Library because I just downloaded it from Gradle.

I tried on an Android 10 SDK 29 on an emulator of a Google Pixel 3 XL.

If you need more infos, I can provide it.

Sincerely,
Charles BEL

**Comment by HBiSoft** [comment]
The problem is with the output file path passed, try adding:

```java
hbRecorder.setOutputPath(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_MOVIES) + "");
```
underneath 
```java
hbRecorder = new HBRecorder(this, this);
```

---
Also, please test on an actual device instead of the emulator.

**Comment by charlesbel** [comment]
I tried to add the line you send but same problem...
I also tried on a phisycal Samsung Galaxy S10+ SDK 29 but it exit with the same error code...

**Comment by HBiSoft** [comment]
The strange thing is what you are saying that the crash happens when you start the recording, but the crash is pointing to `mMediaProjection.stop();`. 

This tells me that there is something else causing `onDestroy` to get called and triggering `MediaProjection.stop();`.

Please try the demo application and provide the entire log (from when you press "Start Now").

**Comment by charlesbel** [comment]
It works with your sample app so I will try to reduce your code to the minimum to see where is the problem, I get back to you soon

**Comment by charlesbel** [comment]
I simplified your code, on your project it works perfectly, but when I transfer it my project, it crashed.
By Simplifing the code, I could know that the error that make crash the app is that error : 

`2020-05-04 13:46:29.479 5098-5098/fr.gooddev.totalspy E/HBRecorderOnError: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION`

**Comment by HBiSoft** [comment]
@charlesbel 
Aha, are you targeting SDK 29? If you are, try reverting back to 28 (just to test).

**Comment by charlesbel** [comment]
I modified my gradle config file to target sdk 28 and it works perfectly !

**Comment by HBiSoft** [comment]
Ok great. I will modify the library later today (or tomorrow morning) to target 29 instead.

**Comment by HBiSoft** [comment]
I have migrated the project to Android 10 (API 29). [Here is the release.](https://github.com/HBiSoft/HBRecorder/releases/tag/0.1.7)

**Comment by osfunapps** [comment]
Thanks for the update! Unfortunately,  `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_MOVIES)` is no longer accessible to Android Q devices, causing crash to some of them. The reason is that `Environment.getExternalStoragePublicDirectory` is deprecated:

> This method was deprecated in API level 29.
To improve user privacy, direct access to shared/external storage devices is deprecated. When an app targets Build.VERSION_CODES.Q, the path returned from this method is no longer directly accessible to apps. Apps can continue to access content stored on shared/external storage by migrating to alternatives such as Context#getExternalFilesDir(String), MediaStore, or Intent#ACTION_OPEN_DOCUMENT. 

You can further read about it here:
[https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String)](https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String))

So that doesn't fully solves the Android Q support. I though about getting the uri from the MediaStore using this:
`MediaStore.Video.Media.RELATIVE_PATH, "Movies/" + "Folder"`
[from Frank's answer](https://stackoverflow.com/questions/57923329/save-and-insert-video-to-gallery-on-android-10) but that doesn't really returns the right path.

I really hope it's just a small change on getting the right public uri of the videos library and not a big change. Google sure took users privacy to a new standard.

**Comment by HBiSoft** [comment]
@osfunapps 
I'm aware of this, that is why there is an option to pass your own path - `hbRecorder.setOutputPath(String)`.

---

If you want the file to be available in the public storage directory, I would recommend the following:

Create a directory in your application directory-
```java
private String mApplicationDir(){
    File imageThumbsDirectory = getBaseContext.getExternalFilesDir("ThumbTemp");
    if(imageThumbsDirectory != null) {
        if (!imageThumbsDirectory.exists()) {
            if (imageThumbsDirectory.mkdir()) ; //directory is created;
        }
    }
}
```
Pass the path of the directory created to `HBRecorder`- 
```java
String appDir = getBaseContext.getExternalFilesDir("ThumbTemp").getAbsolutePath();
hbRecorder.setOutputPath(appDir);
```

Then you can do what Frank mentioned in the link you provided (inside `HBRecorderOnComplete()`):

```java
@Override
    public void HBRecorderOnComplete() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            publicDirURI();
        }else{
            startbtn.setText(R.string.start_recording);
            showLongToast("Saved Successfully");
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                refreshGallery();
            }
        }
}

@RequiresApi(api = Build.VERSION_CODES.Q)
private void publicDirURI() {
    ContentValues valuesvideos;
    valuesvideos = new ContentValues();
    valuesvideos.put(MediaStore.Video.Media.RELATIVE_PATH, "Movies/" + "HBRecorder");
    valuesvideos.put(MediaStore.Video.Media.TITLE, hbRecorder.getFileName());
    valuesvideos.put(MediaStore.Video.Media.DISPLAY_NAME, hbRecorder.getFileName());
    valuesvideos.put(MediaStore.Video.Media.MIME_TYPE, "video/mp4");
    valuesvideos.put(MediaStore.Video.Media.DATE_ADDED, System.currentTimeMillis() / 1000);
    valuesvideos.put(MediaStore.Video.Media.DATE_TAKEN, System.currentTimeMillis());
    valuesvideos.put(MediaStore.Video.Media.IS_PENDING, 1);
    ContentResolver resolver = getContentResolver();
    Uri collection = MediaStore.Video.Media.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY);
    Uri uriSavedVideo = resolver.insert(collection, valuesvideos);

    saveFileToPublicMovies(valuesvideos, uriSavedVideo);
}

// I would recommend doing this in an AsyncTask
private void saveFileToPublicMovies(ContentValues contentValues, Uri uriSavedVideo) {
    ParcelFileDescriptor pfd;
    try {
        pfd = getContentResolver().openFileDescriptor(uriSavedVideo, "w");
        FileOutputStream out = new FileOutputStream(pfd.getFileDescriptor());
        File imageFile = new File(getExternalFilesDir("HBRecorder"), hbRecorder.getFileName());
        FileInputStream in = new FileInputStream(imageFile);
        byte[] buf = new byte[8192];
        int len;
        while ((len = in.read(buf)) > 0) {
            out.write(buf, 0, len);
        }
        out.close();
        in.close();
        pfd.close();

     } catch (Exception e) {
        e.printStackTrace();
    }
    contentValues.clear();
    contentValues.put(MediaStore.Video.Media.IS_PENDING, 0);
    getContentResolver().update(uriSavedVideo, contentValues, null, null);
}
```
I tested this and it is working. it sucks, but it works.

---

I can implement something on the library side to make this simpler. But, there will be some complications because for Android 10 you will pass a `Uri` and pre-10 you will pass a `String`. I will also then have to rely on passing `MediaRecorder` a `FileDescriptor` of the `Uri`, which [can cause further issues](https://stackoverflow.com/a/46897595/5550161).

If you have any suggestions, let me know.

**Comment by osfunapps** [comment]
Thanks for everything. I will use your solution

**Comment by HBiSoft** [comment]
@osfunapps 
Just to clarify one thing - You should not be getting a crash even if you use `getExternalStoragePublicDirectory()` because I added `android:requestlegacyexternalstorage="true"` in the manifest. I tested on a Google Pixel 3XL, running Android 10 and I was able to use `getExternalStoragePublicDirectory`.

If you did get a crash, please let me know.

---

As the [documentation says](https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String)):

>To improve user privacy, direct access to shared/external storage devices is deprecated. When an app targets Build.VERSION_CODES.Q, the path returned from this method is no longer directly accessible to apps.

So, it doesn't say that we cannot use `getExternalStoragePublicDirectory` when targeting Android 10>. It says that `the path returned from this method is no longer directly accessible`. But by adding `android:requestlegacyexternalstorage="true"`, we can access the path.

For more info, have a look at my [question/answer](https://stackoverflow.com/q/60360368/5550161).
