### ISSUE TITLE
Background service

### ISSUE THREAD

**Issue by charlesbel** [HBiSoft/HBRecorder#12]
Hi,
First, I would like to say Awesome Thanks to the developper of this crazy simple library.
I just would like to know if there is a way to use the HBRecorder inside a service.
I know that the screen recording could only be asked from an activity but have you any idea about how to do that like a transparent activity or something similar?
Sincerely,
Charles

**Comment by HBiSoft** [comment]
There is a lot of ways you can achieve this, best is probably using a `BroadcastReceiver`. You will send a broadcast from your `Service` to your `Activity` or `Fragment`. Then you can start `HBRecorder` when you receive the message.

I will be closing this issue because it is not related to the library.
