### ISSUE TITLE
Not able to build 

### ISSUE THREAD

**Issue by aKaushik941** [HBiSoft/HBRecorder#140]
error: cannot access HBRecorderListener
      flutterEngine.getPlugins().add(new com.ed_screen_recorder.ed_screen_recorder.EdScreenRecorderPlugin());
                                ^
  class file for com.hbisoft.hbrecorder.HBRecorderListener not found

I have added all dependencies but still getting this error

**Comment by HBiSoft** [comment]
Hi @aKaushik941,

It's building fine on my side. I did not test building using `EdScreenRecorderPlugin` so I will not be able to help you on that side. But `HBRecorder` by itself, is building fine.

I see you did open an issue on that library as well, so I will be closing this since the problem doesn't seem to be on my side.
