### ISSUE TITLE
Requesting Features

### ISSUE THREAD

**Issue by brittle123** [HBiSoft/HBRecorder#16]
Hello Sir!
Please can you add initial count down timer, orientation mode and pop-up window floating action buttons in this.
Thanks in Advance.

**Comment by HBiSoft** [comment]
<ins>Count down timer:</ins>
I can add an option for you to set a count down timer, but this will still have to be implemented from your application. I can implement this and provide an example in the example application on how you can handle it from your application.

<ins>Orientation mode:</ins>
Can you please explain what you mean with this?

<ins>Floating action buttons:</ins>
As mentioned above, this should also be handled from your application and not from the library's side. I will add an example on how this can be achieved in the example application.

**Comment by brittle123** [comment]
orientation modes,... portrait landscape or both for recorded videos as many sccreen recorders application have option. And i'll be waiting for your addition of count down timer and floating action buttons for recording. Thankyou so much.

**Comment by HBiSoft** [comment]
I will add an option to set the orientation by calling - [setOrientationHint](https://developer.android.com/reference/android/media/MediaRecorder#setOrientationHint(int)) 

I will implement all of this tomorrow.

**Comment by brittle123** [comment]
yayyy,... thanks man,... i'll wait for it.

**Comment by brittle123** [comment]
Hello Sir!,.. you'r going to update your demo application today naa!

**Comment by HBiSoft** [comment]
I have decided not to implement the floating action buttons and the countdown time because it is not part of the library and should be done by the developer. I might implement this at some point, but I'm currently working on other projects. 

I have added the option to set the orientation in the latest release - https://github.com/HBiSoft/HBRecorder/releases/tag/0.1.8

Here is how you can implement a floating action button  - https://medium.com/@kevalpatel2106/create-chat-heads-like-facebook-messenger-32f7f1a62064

You can create a countdown timer like this:

```java
//Declare timer
CountDownTimer cTimer = null;

//start timer function
void startTimer() {
    cTimer = new CountDownTimer(30000, 1000) {
        public void onTick(long millisUntilFinished) {
        }
        public void onFinish() {
        }
    };
    cTimer.start();
}

//cancel timer
void cancelTimer() {
    if(cTimer!=null)
        cTimer.cancel();
}
```

**Comment by brittle123** [comment]
Thankyou so much Sir... it's very helping.
