### ISSUE TITLE
Recorded videos have black bars on the sides.

### ISSUE THREAD

**Issue by AbdulWahab1539** [HBiSoft/HBRecorder#180]
**Describe the bug**
While Testing the app I noticed something Wired The Recorded/Output videos have black bars on the sides. In some devices it happens when we select resolution other then device's native resolution which is 1080p in most of the cases. Whenever we select resolution other than 1080p, the end result/video has black bars on the sides. But Strange thing happens in Pixel 4a 5g device, output videos always have black bars on the sides no matter which resolution is selected. I am attaching all recorded videos with relevant names for easy understanding.

**Can it be reproduced in demo app**
Yes

**HBRecorder version**
Latest version of HBRecorder Sample app at the time of writing

**Device information**
- Make/model -> Google Pixel 4a 5g
- SDK version -> Android 14 (34)
- Make/model -> Vivo S1
- SDK version -> Android 12 (32)

**Video Evidence/Proofs**

https://github.com/user-attachments/assets/c1b7bb32-7645-4575-974f-037fe9c97a47

https://github.com/user-attachments/assets/b64d1a0d-ac24-4efc-8183-54cf299dd688

https://github.com/user-attachments/assets/f1f4ab75-5106-42f8-9267-82d9ce42bb34

https://github.com/user-attachments/assets/bba19a5f-725d-421b-80a3-3fe43679817e

**Comment by HBiSoft** [comment]
My apologies for the late reply. I have tested this and can confirm this happens on my side as well. I have no idea why this is. 

I can understand why it happens when you change it to a resolution other than what your devices resolution is, but I don't know why this always happens with certain Pixel devices.

It could have something to do with the notch cutout, but I'm not sure.

---

I can unfortunately not do anything about this and will be closing the issue.

If you find out why this is happening, please let me know.

**Comment by AbdulWahab1539** [comment]
Hi There! I am Glad that you replied and no need to apology but I can confirm that this issue arises in other devices too like samsung in testing evidence videos  other device is  Vivo

**Comment by HBiSoft** [comment]
@AbdulWahab1539 
I'm aware, but this only happens when you provide a width/height that is not the same aspect ratio as the device.

The way you would go about avoiding this is to keep the aspect ratio. If the device has an aspect ratio of `16:9`, you need to provide a width/height with the same aspect ratio.
