### ISSUE TITLE
some setting are not supperted by your device

### ISSUE THREAD

**Issue by zeeshan5446** [HBiSoft/HBRecorder#81]
hello HBRecorder 
i m facing some issue on android 9 and 11. 
infinix hot 8 android version 9,
im start recording toast show "some setting are not supperted by your device."
pls solve my issuse screenshot is atteched
![error](https://user-images.githubusercontent.com/31355393/127737048-05641c6e-54a8-4454-8be5-f251ba3b0de6.PNG)
![Screenshot_20210731-151340](https://user-images.githubusercontent.com/31355393/127737050-c2add112-5226-4fbe-a7a6-1fab896f6fef.png)

**Comment by khawajaetisam99** [comment]
Hi,

I came across the same problem.
After hours of debugging, I found the solution:

the problem is in the video encoder.
Try to set the video encoder in the file:
hbrecorder\src\main\java\com\hbisoft\hbrecorder\ScreenRecorderservice.java

from:
setvideoEncoderAsInt("DEFAULT");

to:
setvideoEncoderAsInt("H264");
(provided that H264 encoder is supported on all devices and rest of encoders generate errors on few devices)

and issue will be resolved.

**Comment by HBiSoft** [comment]
I will pin this issue because there is a lot of people asking this question.

---
You can use `HBRecorderCodecInfo` to get the supported settings for your specific device.

If you want to use `default`, it's important to first check if your device can set `default` encoder, using a `try`/`catch`. 

You can also make use of the following to get the supported video codec:

https://github.com/HBiSoft/HBRecorder/blob/b34e2b8bc1e34359d3f29224d3c30103abf0e0ae/app/src/main/java/com/hbisoft/hbrecorderexample/MainActivity.java#L137-L145

Above, `defaultVideoEncoder` is the default encoder for the provided mime type(`video/avc`). This is in the demo application and is printed in your logcat as soon as you open the application.

**Comment by Shubhamgarg1072** [comment]
I was trying your sample .But in device like oppo and real me its not  working.

**Comment by limelect** [comment]
On my S6 it is Ok
